# This is a basic workflow to help you get started with Actions

name: build hugo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

  #https://gohugo.io/hosting-and-deployment/hosting-on-github/
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          repository: deletefromuser/hugo-source
          token: ${{ secrets.PAT }}
      
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.68.3"

      - name: build hugo & commit & push
        run: |
          set -e
          printf "\033[0;32mDeploying updates to GitHub...\033[0m\n"
          cd public
          git checkout main
          cd ..
          hugo -t zen
          cd public
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@github.com
          git add .
          msg="rebuilding site $(date)"
          if [ -n "$*" ]; then 
            msg="$*" 
          fi
          git commit -m "$msg"
          git remote -v
          git status
          echo "-------- log start ---------"
          git log -20
          echo "-------- log end ---------"
          git push origin main -v
          echo "-------- log start ---------"
          git log -20
          echo "-------- log end ---------"
