# https://stackoverflow.com/questions/63318249/trigger-github-action-when-github-page-is-published

name: notify profile readme

on: 
  deployment_status

jobs:
  publish:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: notify profile readme.md to regenerate
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.PAT }}" https://api.github.com/repos/deletefromuser/deletefromuser/dispatches -d '{"event_type":"generate"}'
          
